name: flutter_oss_aliyun
description: oss aliyun plugin for flutter and upport STS to access OSS temporarily
repository: https://github.com/huhx/flutter_oss_aliyun
issue_tracker: https://github.com/huhx/flutter_oss_aliyun/issues
topics:
  - aliyun
  - oss
version: 6.4.2

environment:
  sdk: ">=2.17.1 <4.0.0"

dependencies:
  crypto: ^3.0.3
  dio: ^5.2.1
  async: ^2.9.0
  mime: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

screenshots:
  - description: The aliyun oss logo
    path: screenshots/aliyun_oss.png
